language: python
python:
  - "3.8"

before_install:
  - pip install virtualenv
  - pip install pycodestyle
  - python -m pip install -r requirements.txt

script:
  - python -m pytest tests/
  - coverage run --source="src/" -m pytest
  - pycodestyle src/ --ignore=E722,E501,E402