"""add actor

Revision ID: 26a49978fff9
Revises: e5805293c5b7
Create Date: 2021-04-28 02:22:43.715943

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '26a49978fff9'
down_revision = 'e5805293c5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('birthday', sa.Date(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actors')
    # ### end Alembic commands ###
